paths:
  testdata_dir: TestData
  results_dir: Results

llm:
  backend: ollama       # "ollama" or "openai"
  ollama:
    host: http://localhost:11434
    model: llama3.2:latest
  openai:
    model: gpt-4o-mini
    api_key: ""         # optional, can use env variable OPENAI_API_KEY

experiments:
  - id: check_data_type
    prompt_file: Prompts/check_property_data_type.json
    runner: Experiments.check_property_data_type.run_check_property_data_type

  - id: match_idshort_description
    prompt_file: Prompts/match_idshort_description.json
    runner: Experiments.match_idshort_description.run_match_idshort_description
